#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

agent.set_env("LDAP_DOMAIN", data.get("ldap_domain", ""))
agent.set_env("AUTH_METHOD", 'BASIC' if data.get("ldap_domain", "basic") == "basic" else 'LDAP')
agent.set_env("AUTH_PASS", data.get("auth_pass", ""))
agent.set_env("AUTH_USER", data.get("auth_user", ""))
