#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

agent.set_env("LDAP_DOMAIN", data["ldap_domain"])
agent.set_env("AUTH_METHOD", 'BASIC' if data["ldap_domain"] == "basic" else 'LDAP')
agent.set_env("AUTH_PASS", data.get("auth_pass", ""))
agent.set_env("AUTH_USER", data.get("auth_user", ""))

# bind to the user domain
if data["ldap_domain"] != "basic":
    agent.bind_user_domains([data["ldap_domain"]])
