#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        "TRAEFIK_HOST",
        "TRAEFIK_HTTP2HTTPS",
        "TRAEFIK_LETS_ENCRYPT",
    ]:
    agent.set_env(evar, original_environment[evar])

agent.set_env("LDAP_DOMAIN", original_environment.get("ldap_domain", ""))
agent.set_env("AUTH_METHOD", 'BASIC' if original_environment.get("ldap_domain", "") == "" else 'LDAP')
agent.set_env("AUTH_PASS", original_environment.get("auth_pass", ""))
agent.set_env("AUTH_USER", original_environment.get("auth_user", ""))
